---

- name: Ansible Terraform Wrapper
  hosts: localhost
  vars_files: 
   - ./env_vars.yml
  tasks: 
#  - debug: 
#      var: grafana_folders
#
  - debug: 
      var: grafana_dashboards

  - set_fact: 
      full_dashboard_list: "{{ full_dashboard_list|default([]) + item.value }}"
    loop: "{{ grafana_dashboards|dict2items }}"
  
  - set_fact: 
      uniq_dashboard_list: "{{ full_dashboard_list | unique }}"
  
  - debug: 
      var: uniq_dashboard_list

  - debug: 
      msg: "{{ item.dashboard_file }}"
    loop: "{{ uniq_dashboard_list }}"

  - name: Make sure dashboards folder exists
    file:
      path: ./dashboards
      state: directory 
    delegate_to: localhost

  - name: Copy template dashboards 
    copy: 
      src: "../../grafana-dashboards/docker-dashboards/{{ item.dashboard_file }}"
      dest: "./dashboards/{{ item.dashboard_file }}"
    loop: "{{ uniq_dashboard_list }}"
    delegate_to: localhost

  - name: Take Grafana templates and Update Template Json Datastore structure
    replace:
      dest: "./dashboards/{{ item.dashboard_file }}"
      regexp: '"(?:\${)?DS_[A-Z0-9_-]+(?:})?"'
      replace: '"{{ item.grafana_datastore }}"'
    loop: "{{ uniq_dashboard_list }}"
    delegate_to: localhost




